In [1]:
!pip install -q tensorflow==2.12.0
!pip install -q keras-nlp

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.7/527.7 kB 14.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 63.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 524.1/524.1 MB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 90.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 116.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 44.8 MB/s eta 0:00:00


In [2]:
import keras_nlp

import numpy as np
from tensorflow import keras
import tensorflow as tf

# Understand Tokenizer and Preprocessor

In [3]:
gpt2_tokenizer = keras_nlp.models.GPT2Tokenizer.from_preset("gpt2_base_en")
gpt2_preprocessor = keras_nlp.models.GPT2CausalLMPreprocessor.from_preset("gpt2_base_en")

456318/456318 [==============================] - 0s 1us/step


In [4]:
text = "In case I don't see you, I wish you good morning good evening and good night!"

print(gpt2_tokenizer(text))
print(gpt2_preprocessor(text))

tf.Tensor(
[ 818 1339  314  836  470  766  345   11  314 4601  345  922 3329  922
 6180  290  922 1755    0], shape=(19,), dtype=int32)
({'token_ids': <tf.Tensor: shape=(1024,), dtype=int32, numpy=array([50256,   818,  1339, ...,     0,     0,     0], dtype=int32)>, 'padding_mask': <tf.Tensor: shape=(1024,), dtype=bool, numpy=array([ True,  True,  True, ..., False, False, False])>}, <tf.Tensor: shape=(1024,), dtype=int32, numpy=array([ 818, 1339,  314, ...,    0,    0,    0], dtype=int32)>, <tf.Tensor: shape=(1024,), dtype=bool, numpy=array([ True,  True,  True, ..., False, False, False])>)


In [5]:
text = "Our base is under attack"
gpt2_causal_lm = keras_nlp.models.GPT2CausalLM.from_preset("gpt2_base_en")
print(gpt2_causal_lm.predict([text]))

497986112/497986112 [==============================] - 17s 0us/step


1/1 [==============================] - 13s 13s/step
[[[ -43.431667  -39.83638   -43.065968 ...  -54.0877    -54.34514
    -42.364414]
  [ -83.18129   -83.16285   -84.15776  ...  -81.79299   -86.67058
    -81.4228  ]
  [ -83.4646    -85.13435   -87.51862  ...  -89.974754  -92.49895
    -85.27918 ]
  ...
  [ -99.60134  -101.788315 -101.03881  ... -110.80368  -109.99257
    -96.18486 ]
  [ -99.728615 -101.90072  -101.15395  ... -110.91753  -110.112526
    -96.30464 ]
  [ -87.54202   -88.00072   -86.205734 ...  -97.40389   -95.16851
    -85.28139 ]]]


In [6]:
custom_preprocessor = keras_nlp.models.GPT2CausalLMPreprocessor.from_preset(
    "gpt2_base_en",
    sequence_length=8,
)
gpt2_causal_lm.preprocessor = custom_preprocessor
print(gpt2_causal_lm.predict([text]))

1/1 [==============================] - 20s 20s/step
[[[ -43.431686  -39.83641   -43.06595  ...  -54.087673  -54.345158
    -42.36443 ]
  [ -83.18127   -83.16288   -84.157745 ...  -81.79299   -86.67071
    -81.42276 ]
  [ -83.46462   -85.134384  -87.518585 ...  -89.974594  -92.4989
    -85.27921 ]
  ...
  [ -96.97779  -101.54622  -105.41487  ... -113.38185  -114.14488
   -101.33537 ]
  [ -91.512184  -84.49864   -86.97461  ... -104.81543  -105.664566
    -92.89865 ]
  [ -85.72317   -86.26408   -83.61421  ...  -96.93445   -94.53073
    -84.692696]]]


In [7]:
preprocessed_text = gpt2_preprocessor([text])
gpt2_causal_lm.preprocessor = None
print(gpt2_causal_lm.predict(preprocessed_text[0]))

1/1 [==============================] - 6s 6s/step
[[[ -43.431667  -39.83638   -43.065968 ...  -54.0877    -54.34514
    -42.364414]
  [ -83.18129   -83.16285   -84.15776  ...  -81.79299   -86.67058
    -81.4228  ]
  [ -83.4646    -85.13435   -87.51862  ...  -89.974754  -92.49895
    -85.27918 ]
  ...
  [ -99.60134  -101.788315 -101.03881  ... -110.80368  -109.99257
    -96.18486 ]
  [ -99.728615 -101.90072  -101.15395  ... -110.91753  -110.112526
    -96.30464 ]
  [ -87.54202   -88.00072   -86.205734 ...  -97.40389   -95.16851
    -85.28139 ]]]


# Generate Text and Custom Sampler


In [8]:
gpt2_causal_lm = keras_nlp.models.GPT2CausalLM.from_preset("gpt2_base_en")
gpt2_causal_lm.generate("I think basketball is fun because", max_length=50)

"I think basketball is fun because it is an exciting sport and a fun game. I love to play basketball. I love to play the game of basketball. It's fun to see the game of basketball. It's fun to see the sport of"

In [9]:
# Use contrastive search.
gpt2_causal_lm.compile(sampler="contrastive")
gpt2_causal_lm.generate("I think basketball is fun because", max_length=50)

"I think basketball is fun because it's fun to watch. It's fun to watch the game. It's fun to watch the game. It's fun to watch the game. It's fun to watch the game. It's fun to watch"

In [10]:
# Use custom sampler configurations.
sampler = keras_nlp.samplers.TopPSampler(p=0.1)
gpt2_causal_lm.compile(sampler=sampler)
gpt2_causal_lm.generate("I think basketball is fun because", max_length=50)

"I think basketball is fun because it's fun to watch. It's fun to watch the game. It's fun to watch the game. It's fun to watch the game. It's fun to watch the game. It's fun to watch"

# Finetune your model

Let's try finetuning our GPT2 model with Dolly2 dataset.

In [11]:
!pip install -q datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 486.2/486.2 kB 22.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 15.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 24.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 17.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 30.4 MB/s eta 0:00:00


In [12]:
# Load Dolly2 from HuggingFace
from datasets import load_dataset

dolly = load_dataset("databricks/databricks-dolly-15k", split="train")

Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Dataset json downloaded and prepared to /root/.cache/huggingface/datasets/databricks___json/databricks--databricks-dolly-15k-7427aa6e57c34282/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96. Subsequent calls will reuse this data.


In [13]:
print(dolly[0])

{'instruction': 'When did Virgin Australia start operating?', 'context': "Virgin Australia, the trading name of Virgin Australia Airlines Pty Ltd, is an Australian-based airline. It is the largest airline by fleet size to use the Virgin brand. It commenced services on 31 August 2000 as Virgin Blue, with two aircraft on a single route. It suddenly found itself as a major airline in Australia's domestic market after the collapse of Ansett Australia in September 2001. The airline has since grown to directly serve 32 cities in Australia, from hubs in Brisbane, Melbourne and Sydney.", 'response': 'Virgin Australia commenced services on 31 August 2000 as Virgin Blue, with two aircraft on a single route.', 'category': 'closed_qa'}


In [14]:
prompt_template = {
    "prompt_input": "Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Input:\n{input}\n\n### Response:\n{response}",
    "prompt_no_input": "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Response:\n{response}",
}

In [15]:
def format_text(data):
    if len(data["context"]) == 0:
        full_text = prompt_template["prompt_no_input"].format(
            instruction=data["instruction"],
            input=data["context"],
            response=data["response"],
        )
    else:
        full_text = prompt_template["prompt_input"].format(
            instruction=data["instruction"],
            input=data["context"],
            response=data["response"],
        )

    return full_text

In [16]:
dolly_text = []
for data in dolly:
    dolly_text.append(format_text(data))

In [17]:
dolly_tf_data = tf.data.Dataset.from_tensor_slices(dolly_text)
dolly_tf_data = dolly_tf_data.batch(4).cache().prefetch(tf.data.AUTOTUNE)

In [18]:
# To speed up training and generation, we use preprocessor of length 512
# instead of full length 1024.
preprocessor = keras_nlp.models.GPT2CausalLMPreprocessor.from_preset(
    "gpt2_base_en",
    sequence_length=512,
)
gpt2_causal_lm = keras_nlp.models.GPT2CausalLM.from_preset(
    "gpt2_base_en", preprocessor=preprocessor
)

In [19]:
num_epochs = 2
lr = tf.keras.optimizers.schedules.PolynomialDecay(
    5e-5,
    decay_steps=dolly_tf_data.cardinality() * num_epochs,
    end_learning_rate=0.0,
)
gpt2_causal_lm.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.AdamW(lr, weight_decay=0.001),
)

In [20]:
gpt2_causal_lm.fit(dolly_tf_data.take(100), epochs=num_epochs)

Epoch 1/2
100/100 [==============================] - 110s 506ms/step - loss: 0.9195
Epoch 2/2
100/100 [==============================] - 56s 558ms/step - loss: 0.7897


In [21]:
gpt2_causal_lm.generate("Why is basketball interesting?", max_length=100)

'Why is basketball interesting?\n\nThe answer to this question may surprise some, as basketball is a sport that appeals to a wide variety, from children to adults. The sport has many elements that are unique and unique, and it is also a great way to experience a variety of sports and activities.\n\nThere are a variety of sports and activities to be played in basketball, ranging from swimming, golf, basketball, baseball, soccer and tennis to soccer. Basketball is also a great way for'