In [ ]:
!pip install -q keras-nlp

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.7/527.7 kB 25.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 108.1 MB/s eta 0:00:00


In [ ]:
import keras_nlp

import numpy as np
from tensorflow import keras
import tensorflow as tf

# Understand Tokenizer and Preprocessor

In [ ]:
gpt2_tokenizer = keras_nlp.models.GPT2Tokenizer.from_preset("gpt2_base_en")
gpt2_preprocessor = keras_nlp.models.GPT2CausalLMPreprocessor.from_preset("gpt2_base_en")

In [ ]:
text = "In case I don't see you, I wish you good morning good evening and good night!"

print(gpt2_tokenizer(text))
print(gpt2_preprocessor(text))

tf.Tensor(
[ 818 1339  314  836  470  766  345   11  314 4601  345  922 3329  922
 6180  290  922 1755    0], shape=(19,), dtype=int32)
({'token_ids': <tf.Tensor: shape=(1024,), dtype=int32, numpy=array([50256,   818,  1339, ...,     0,     0,     0], dtype=int32)>, 'padding_mask': <tf.Tensor: shape=(1024,), dtype=bool, numpy=array([ True,  True,  True, ..., False, False, False])>}, <tf.Tensor: shape=(1024,), dtype=int32, numpy=array([ 818, 1339,  314, ...,    0,    0,    0], dtype=int32)>, <tf.Tensor: shape=(1024,), dtype=bool, numpy=array([ True,  True,  True, ..., False, False, False])>)


In [ ]:
text = "Our base is under attack"
gpt2_causal_lm = keras_nlp.models.GPT2CausalLM.from_preset("gpt2_base_en")
print(gpt2_causal_lm.predict([text]))

1/1 [==============================] - 25s 25s/step


array([[[ -43.431664,  -39.8364  ,  -43.065933, ...,  -54.087666,
          -54.34513 ,  -42.364414],
        [ -87.39803 ,  -86.5145  ,  -88.9109  , ...,  -94.12491 ,
          -94.52537 ,  -87.32713 ],
        [ -80.17603 ,  -81.15189 ,  -85.28315 , ...,  -84.272064,
          -88.86102 ,  -81.23149 ],
        ...,
        [-107.97836 , -109.110275, -109.169266, ..., -119.05172 ,
         -117.997406, -105.17837 ],
        [-107.8259  , -108.94652 , -109.00359 , ..., -118.88552 ,
         -117.84095 , -105.0213  ],
        [ -90.82515 ,  -90.467064,  -88.67217 , ..., -101.283646,
          -98.79904 ,  -89.55116 ]]], dtype=float32)

In [ ]:
custom_preprocessor = keras_nlp.models.GPT2CausalLMPreprocessor.from_preset(
    "gpt2_base_en",
    sequence_length=8,
)
gpt2_causal_lm.preprocessor = custom_preprocessor
print(gpt2_causal_lm.predict([text]))

1/1 [==============================] - 10s 10s/step


array([[[ -43.431664,  -39.8364  ,  -43.065933, ...,  -54.087666,
          -54.34513 ,  -42.364414],
        [ -87.39804 ,  -86.51452 ,  -88.910904, ...,  -94.12491 ,
          -94.52539 ,  -87.327156],
        [ -80.17605 ,  -81.15191 ,  -85.283165, ...,  -84.272064,
          -88.86103 ,  -81.23149 ],
        ...,
        [-145.93472 , -146.0797  , -153.86163 , ..., -157.69104 ,
         -155.10272 , -148.94597 ],
        [ -97.729164,  -97.30452 , -102.732544, ..., -103.058174,
         -104.87569 ,  -98.0504  ],
        [-111.72096 , -113.96916 , -117.91676 , ..., -122.19133 ,
         -119.252335, -114.06735 ]]], dtype=float32)

In [ ]:
preprocessed_text = gpt2_preprocessor([text])
gpt2_causal_lm.preprocessor = None
print(gpt2_causal_lm.predict(preprocessed_text[0]))

1/1 [==============================] - 18s 18s/step


array([[[ -43.431664,  -39.8364  ,  -43.065933, ...,  -54.087666,
          -54.34513 ,  -42.364414],
        [ -87.39803 ,  -86.5145  ,  -88.9109  , ...,  -94.12491 ,
          -94.52537 ,  -87.32713 ],
        [ -80.17603 ,  -81.15189 ,  -85.28315 , ...,  -84.272064,
          -88.86102 ,  -81.23149 ],
        ...,
        [-107.97836 , -109.110275, -109.169266, ..., -119.05172 ,
         -117.997406, -105.17837 ],
        [-107.8259  , -108.94652 , -109.00359 , ..., -118.88552 ,
         -117.84095 , -105.0213  ],
        [ -90.82515 ,  -90.467064,  -88.67217 , ..., -101.283646,
          -98.79904 ,  -89.55116 ]]], dtype=float32)

# Generate Text and Custom Sampler


In [ ]:
gpt2_causal_lm = keras_nlp.models.GPT2CausalLM.from_preset("gpt2_base_en")
gpt2_causal_lm.generate("I think basketball is fun because", max_length=50)

497986112/497986112 [==============================] - 25s 0us/step


"I think basketball is fun because it is an exciting sport and a fun game. I love to play basketball. I love to play the game of basketball. It's fun to see the game of basketball. It's fun to see the sport of"

In [ ]:
# Use contrastive search.
gpt2_causal_lm.compile(sampler="contrastive")
gpt2_causal_lm.generate("I think basketball is fun because", max_length=50)

"I think basketball is fun because it's fun to watch. It's fun to watch the game. It's fun to watch the game. It's fun to watch the game. It's fun to watch the game. It's fun to watch"

In [ ]:
# Use custom sampler configurations.
sampler = keras_nlp.samplers.TopPSampler(p=0.1)
gpt2_causal_lm.compile(sampler=sampler)
gpt2_causal_lm.generate("I think basketball is fun because", max_length=50)

"I think basketball is fun because it's fun to watch. It's fun to watch the game. It's fun to watch the game. It's fun to watch the game. It's fun to watch the game. It's fun to watch"

# Finetune your model

Let's try finetuning our GPT2 model with Dolly2 dataset.

In [ ]:
!pip install -q datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.6/474.6 kB 33.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 15.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 27.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 17.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 56.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.8/236.8 kB 24.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 16.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 34.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.6/149.6 kB 21.6 MB/s eta 0:00:00


In [ ]:
# Load Dolly2 from HuggingFace
from datasets import load_dataset

dolly = load_dataset("databricks/databricks-dolly-15k", split="train")

Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Dataset json downloaded and prepared to /root/.cache/huggingface/datasets/databricks___json/databricks--databricks-dolly-15k-6e0f9ea7eaa0ee08/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4. Subsequent calls will reuse this data.


In [ ]:
print(dolly[0])

{'instruction': 'When did Virgin Australia start operating?',
 'context': "Virgin Australia, the trading name of Virgin Australia Airlines Pty Ltd, is an Australian-based airline. It is the largest airline by fleet size to use the Virgin brand. It commenced services on 31 August 2000 as Virgin Blue, with two aircraft on a single route. It suddenly found itself as a major airline in Australia's domestic market after the collapse of Ansett Australia in September 2001. The airline has since grown to directly serve 32 cities in Australia, from hubs in Brisbane, Melbourne and Sydney.",
 'response': 'Virgin Australia commenced services on 31 August 2000 as Virgin Blue, with two aircraft on a single route.',
 'category': 'closed_qa'}

In [ ]:
prompt_template = {
    "prompt_input": "Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Input:\n{input}\n\n### Response:\n{response}",
    "prompt_no_input": "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Response:\n{response}",
}

In [ ]:
def format_text(data):
    if len(data["context"]) == 0:
        full_text = prompt_template["prompt_no_input"].format(
            instruction=data["instruction"],
            input=data["context"],
            response=data["response"],
        )
    else:
        full_text = prompt_template["prompt_input"].format(
            instruction=data["instruction"],
            input=data["context"],
            response=data["response"],
        )

    return full_text

In [ ]:
dolly_text = []
for data in dolly:
    dolly_text.append(format_text(data))

In [ ]:
dolly_tf_data = tf.data.Dataset.from_tensor_slices(dolly_text)
dolly_tf_data = dolly_tf_data.batch(4).cache().prefetch(tf.data.AUTOTUNE)

In [ ]:
# To speed up training and generation, we use preprocessor of length 512
# instead of full length 1024.
preprocessor = keras_nlp.models.GPT2CausalLMPreprocessor.from_preset(
    "gpt2_base_en",
    sequence_length=512,
)
gpt2_causal_lm = keras_nlp.models.GPT2CausalLM.from_preset(
    "gpt2_base_en", preprocessor=preprocessor
)

In [ ]:
num_epochs = 2
lr = tf.keras.optimizers.schedules.PolynomialDecay(
    5e-5,
    decay_steps=dolly_tf_data.cardinality() * num_epochs,
    end_learning_rate=0.0,
)
gpt2_causal_lm.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.AdamW(lr, weight_decay=0.001),
)

In [ ]:
gpt2_causal_lm.fit(dolly_tf_data.take(100), epochs=num_epochs)

Epoch 1/2
100/100 [==============================] - 56s 557ms/step - loss: 0.8368
Epoch 2/2
100/100 [==============================] - 55s 551ms/step - loss: 0.7525


In [ ]:
gpt2_causal_lm.generate("Why is basketball interesting?", max_length=100)

"Why is basketball interesting?\n\nThe answer to that question depends on which team you're watching. You can tell the difference between the best teams in the NBA and the best teams in the NBA by how well each team has won or lost. The NBA is a great game, and there are plenty of great teams out there, including the Chicago Bulls, who lost to the Miami Heat in the first round of the playoffs, to the Golden State Warriors, who are in the midst of a historic"